version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y git
      - rm -rf capillary-cloud-tf/stacks/*
      - cp -r $CODEBUILD_SRC_DIR_STACK/$STACK_SUBDIRECTORY capillary-cloud-tf/stacks/$STACK_NAME
      - cp -r $CODEBUILD_SRC_DIR_STACK/$STACK_SUBDIRECTORY/schema capillary-cloud-tf/schema
      - cp -r $CODEBUILD_SRC_DIR_STACK/$STACK_SUBDIRECTORY/seed_data capillary-cloud-tf/seed_data
      - if [ -d "$CODEBUILD_SRC_DIR_STACK/$STACK_SUBDIRECTORY/database_views" ]; then cp -r $CODEBUILD_SRC_DIR_STACK/$STACK_SUBDIRECTORY/database_views capillary-cloud-tf/database_views; fi
      - cd capillary-cloud-tf/tfaws/
      - terraform init
      - if terraform workspace select $CLUSTER_ID; then echo "workspace exists"; else terraform workspace new $CLUSTER_ID; fi
      - terraform apply -target module.overrides -auto-approve -no-color -parallelism=30
  build:
    commands:
      - terraform apply -target module.infra -auto-approve -no-color -parallelism=10
      - terraform apply -target module.iam -auto-approve -no-color -parallelism=10
      - terraform apply -target module.application -auto-approve -no-color -parallelism=10
      - terraform apply -target module.disaster-recovery -auto-approve -no-color -parallelism=10
  post_build:
    commands:
      - python3 scripts/report.py
artifacts:
  files:
    - capillary-cloud-tf/tfaws/fetched_builds/**/*
    - capillary-cloud-tf/tfaws/*.json