
-- start  Schema : voucher_series

CREATE TABLE `voucher_series` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `org_id` int(11) NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `series_type` enum('CAMPAIGN','DVS','ALLIANCE','GOODWILL','LOYALTY','UNDEFINED','TIMELINE','REFERRAL') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `client_handling_type` enum('DISC_CODE','RULE_BASED','DISC_GV','DISC_PROMO','DISC_CODE_PIN','AMOUNT_BASED','ARTICLE_BASED','GENERIC','EXTERNAL_ISSUAL') COLLATE utf8mb4_unicode_ci NOT NULL,
  `discount_code` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `valid_till_date` date DEFAULT NULL,
  `valid_days_from_create` int(11) NOT NULL,
  `expiry_strategy_type` enum('DAYS','MONTHS','MONTHS_END','SERIES_EXPIRY') COLLATE utf8mb4_unicode_ci DEFAULT 'DAYS',
  `expiry_strategy_value` int(11) DEFAULT '0',
  `max_create` int(11) NOT NULL DEFAULT '-1',
  `max_redeem` int(11) NOT NULL DEFAULT '-1' COMMENT 'Number of vouchers in this series that can be used in future',
  `transferrable` tinyint(1) NOT NULL DEFAULT '0',
  `any_user` tinyint(1) NOT NULL DEFAULT '0',
  `same_user_multiple_redeem` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Can the same user redeem a voucher multiple times',
  `allow_referral_existing_users` tinyint(1) NOT NULL COMMENT 'Allow referral for existing users ?',
  `multiple_use` tinyint(1) NOT NULL DEFAULT '0',
  `is_validation_required` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Is validation code checking required',
  `valid_with_discounted_item` tinyint(1) NOT NULL DEFAULT '1',
  `created_by` bigint(20) NOT NULL,
  `num_issued` int(11) NOT NULL DEFAULT '0',
  `num_redeemed` int(11) NOT NULL DEFAULT '0',
  `created` datetime NOT NULL,
  `last_used` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `series_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sms_template` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'sms template to be used when resending vouchers',
  `disable_sms` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'If selected, sms for the series should be disabled',
  `info` text COLLATE utf8mb4_unicode_ci COMMENT 'Detailed Description',
  `allow_multiple_vouchers_per_user` tinyint(1) NOT NULL DEFAULT '0',
  `do_not_resend_existing_voucher` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'If true, does not send the voucher back to the customer again',
  `mutual_exclusive_series_ids` mediumtext COLLATE utf8mb4_unicode_ci COMMENT 'json array of voucher series ids. A voucher for a user can be present in only one of them',
  `store_ids_json` mediumtext COLLATE utf8mb4_unicode_ci COMMENT 'ids of the stores where the series is applicable',
  `dvs_enabled` tinyint(1) DEFAULT NULL,
  `dvs_expiry_date` date DEFAULT NULL,
  `priority` int(11) DEFAULT NULL,
  `terms_and_condition` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signal_redemption_event` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'If true, signals a voucher redemption event',
  `sync_to_client` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Selectively exclude the vouchers that are sent to the client',
  `short_sms_template` text COLLATE utf8mb4_unicode_ci COMMENT 'Used for clubbing of sms',
  `max_vouchers_per_user` int(11) NOT NULL DEFAULT '-1' COMMENT 'Maximum number of vouchers per user in the series. -1 implies unlimited',
  `min_days_between_vouchers` int(11) NOT NULL DEFAULT '-1' COMMENT 'minimum number of days between two vouchers',
  `max_referrals_per_referee` int(11) NOT NULL DEFAULT '-1' COMMENT 'maximum number of times any referee can be referred by any referrer',
  `show_pin_code` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Ability to control the display of pin code at series level',
  `discount_on` enum('BILL','ITEM') COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Whether the discount is on BILL OR ITEM',
  `discount_type` enum('PERC','ABS') COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Whether the discount is a percentage or absolute value',
  `discount_value` float DEFAULT NULL COMMENT 'value corresponding to discount_type',
  `dvs_items` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'To contain descriptions of dvs items to be printed on paper vouchers',
  `redemption_range` text COLLATE utf8mb4_unicode_ci COMMENT 'To Define Redemption Range for the voucher series in {''dom:xyz'' , ''dow:xyz'' , ''hours:xyz''} format',
  `min_bill_amount` double NOT NULL DEFAULT '0',
  `max_bill_amount` double NOT NULL DEFAULT '0',
  `redeem_at_store` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `campaign_id` bigint(20) NOT NULL DEFAULT '-1',
  `tag` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `max_redemptions_in_series_per_user` int(11) NOT NULL DEFAULT '-1',
  `min_days_between_redemption` int(11) NOT NULL DEFAULT '-1',
  `redemption_valid_from` date DEFAULT NULL,
  `redeem_store_type` varchar(20) CHARACTER SET utf8mb4 DEFAULT 'redeemable_stores',
  `offline_redeem_type` tinyint(1) NOT NULL DEFAULT '0',
  `source_org_id` int(11) DEFAULT NULL COMMENT 'source org which can issue this voucher.Used in NCA for current org',
  `issue_to_loyalty` tinyint(1) DEFAULT '0' COMMENT 'issue the voucher to loyalty customers',
  `old_flow_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `pre_redeem_event_required` tinyint(1) NOT NULL DEFAULT '0',
  `redemption_valid_after_days` int(3) NOT NULL DEFAULT '0',
  `purpose` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `metadata` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`,`org_id`),
  KEY `org_id` (`org_id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `org_time_idx` (`last_used`,`org_id`),
  KEY `auto_time_idx` (`last_used`) USING BTREE,
  KEY `source_org_id` (`source_org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=16;


-- end  Schema : voucher_series