
-- start  Schema : COLLATION_CHARACTER_SET_APPLICABILITY

CREATE TEMPORARY TABLE `COLLATION_CHARACTER_SET_APPLICABILITY` (
  `COLLATION_NAME` varchar(32) NOT NULL DEFAULT '',
  `CHARACTER_SET_NAME` varchar(32) NOT NULL DEFAULT ''
) ENGINE=MEMORY DEFAULT CHARSET=utf8;


-- end  Schema : COLLATION_CHARACTER_SET_APPLICABILITY