
-- start  Schema : INNODB_FT_DEFAULT_STOPWORD

CREATE TEMPORARY TABLE `INNODB_FT_DEFAULT_STOPWORD` (
  `value` varchar(18) NOT NULL DEFAULT ''
) ENGINE=MEMORY DEFAULT CHARSET=utf8;


-- end  Schema : INNODB_FT_DEFAULT_STOPWORD