
-- start  Schema : INNODB_FT_DELETED

CREATE TEMPORARY TABLE `INNODB_FT_DELETED` (
  `DOC_ID` bigint(21) unsigned NOT NULL DEFAULT '0'
) ENGINE=MEMORY DEFAULT CHARSET=utf8;


-- end  Schema : INNODB_FT_DELETED