
-- start  Schema : queued_jobs

CREATE TABLE `queued_jobs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `org_id` int(11) NOT NULL,
  `ref_id` int(11) DEFAULT NULL COMMENT 'The job id generated by the thrift service',
  `scheduler_task_id` int(11) NOT NULL,
  `template_id` int(11) NOT NULL,
  `profile` smallint(3) unsigned DEFAULT NULL,
  `queued_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `filename` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `execution_status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fileservice_handle` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fileservice_version` tinyint(3) NOT NULL DEFAULT '1',
  `ftp_server_config` mediumtext COLLATE utf8mb4_unicode_ci,
  `scp_server_config` mediumtext COLLATE utf8mb4_unicode_ci,
  `mailing_list` mediumtext COLLATE utf8mb4_unicode_ci,
  `export_job_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'created by the export scheduler job - thrift service',
  `filters` longtext COLLATE utf8mb4_unicode_ci,
  `columns` mediumtext COLLATE utf8mb4_unicode_ci,
  `file_format` mediumtext COLLATE utf8mb4_unicode_ci,
  `additional_details` mediumtext COLLATE utf8mb4_unicode_ci COMMENT 'Json text to save all the additional details; including the thrift response',
  `export_to` enum('FTP','EXTERNAL_S3') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'FTP',
  PRIMARY KEY (`id`),
  KEY `template_id` (`org_id`,`template_id`),
  KEY `queued_on` (`org_id`,`queued_on`),
  KEY `filename_idx` (`org_id`,`filename`),
  KEY `scheduler_id` (`org_id`,`scheduler_task_id`,`queued_on`),
  KEY `export_job_idx` (`export_job_id`),
  KEY `ref_id` (`org_id`,`ref_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=16;


-- end  Schema : queued_jobs